### ISSUE TITLE
Digitize custom plots, SI unit support, package creation

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/svgdigitizer#177]
This will be a larger overhaul of the digitizer functionalities. Currently, we have a class for one type of custom plot (CV). Some of the functionalities will likely be identical when other custom plots for other data types are created. Among those is a `scan rate` that allows for reconstructing a time axis.

Requested was also the option to save data as they appear in the Figure instead of saving data in SI units.(see #165)

To clearly understand which units are used in the saved data, it would be wise to always save the data as a frictionless data package. Currently, we only save a JSON with some minimum information, and data package creation is only possible in the CV module. The approach will be different from that proposed in  #148.

-----
Roadmap
- [x] Create a new SVGfigure class, which serves as the parent class for specific plots such as CV. (see #178)
- [x] Add argument `SI=Fals/True` to Figureplot (see #178)
- [x] Update CLI
  - [x] SI flag (see #178)
  - [x] remove flag `--package` and make package creation mandatory (see #182)
- [x] Update documentation for all those changes
  - [x] Update sphinx docu (#189 )
-----
Fixes
- [x] #148 
- [x] #165 
- [x] #167
