### ISSUE TITLE
Document and Doctest everything

### ISSUE THREAD

**Issue by saraedum** [echemdb/svgdigitizer#73]
Currently, the following is not doctested and/or documented:

* [x] `svgdigitizer` (the package itself) (see #125)
* [x] `svgdigitizer.cv` (the module itself)
   * [x] Add link to workflow.md (see #87)
* [x] `svgdigitizer.cv.CV` (see #80)
   * [x] Add link to workflow.md (see #87)
* [x] `svgdigitizer.cv.CV.axis_properties` (see #80)
* [x] `svgdigitizer.cv.CV.x_label` (see #80)
* [x] `svgdigitizer.cv.CV.df` 
    * [x] Implemented for a simple svg file (see #80)
* [x] `svgdigitizer.cv.CV._add_U_axis()` (see #80)
* [x] `svgdigitizer.cv.CV._add_I_axis()` (see #80)
* [x] `svgdigitizer.cv.CV._add_time_axis()` (see #80)
* [x] `svgdigitizer.cv.CV.plot()`  (see #78)
* [x] `svgdigitizer.cv.CV.metadata` (see #80)
* [x] `svgdigitizer.__main__` (see #86)
* [x] `svgdigitizer.__main__.cli()` (see #102)
* [x] `svgdigitizer.__main__.plot()` (see #86)
* [x] `svgdigitizer.__main__.digitize()` (see #102)
* [x] `svgdigitizer.__main__.cv()` (see #102)
* [x] `svgdigitizer.__main__.paginate()` (see #102)
* [x] `svgdigitizer.svgplot` (the module itself) (see #102)
* [x] `svgdigitizer.svgplot.SVGPlot.labeled_paths` (see #102)
* [x] `svgdigitizer.svg` (the module itself) (see #102)
* [x] `svgdigitizer.svg.LabeledPath.path_points()` (see #221)
* [x] `svgdigitizer.svg.LabeledPath.points`  (see #221)
* [x] `svgdigitizer.svg.LabeledPath.__repr__()` (see #221)
* [x] `svgdigitizer.svg.Text.__repr__()` (see #221)
* [x] `svgdigitizer.svg.Text.__str__()` (see #221)
* [x] `svgdigitizer.test.cli` (see #221)
* [x] `svgdigitizer.test.cli.invoke()` (see #86)
* [x] `svgdigitizer.test.cli.TemporaryData()` (see #86)
* [ ]  `svgdigitizer.test.cli.TemporaryData.__enter__()`
* [ ]  `svgdigitizer.test.cli.TemporaryData.__exit__()`

The following are not documented and doctested but that's Ok. The classes should be documented and doctested instead since this information does not show up in the documentation anywhere anyway:

* `svgdigitizer.cv.CV.__init__()`
* `svgdigitizer.svgplot.SVGPlot.__init__()`
* `svgdigitizer.svg.SVG.__init__()`
* `svgdigitizer.svg.LabeledPaths.__init__()`
* `svgdigitizer.svg.LabeledPath.__init__()`
* `svgdigitizer.svg.Text.__init__()`
* `svgdigitizer.test.cli.TemporaryData.__init__()`

**Comment by DunklesArchipel** [comment]
@saraedum How should we doctest or document the CLI.

I found the following solutions. Both require a filename (which should point to an existing file). Should we use an example from the testfiles?

This is sort of the suggestion from [click documentation](https://click.palletsprojects.com/en/8.0.x/testing/):
```python
from click.testing import CliRunner

runner = CliRunner()
result = runner.invoke(your_func, ['your', 'args', 'here'], catch_exceptions=False)

assert result.exit_code == 0
```

Another approach would be the following:
```python
from svgdigitizer.__main__ import digitize
digitize.callback('test.svg', sampling_interval=None)
```

**Comment by saraedum** [comment]
Does the latter approach actually need a filename or can you also pass in a file object directly? If so, then you can create the SVG in memory as we do in many of the other doctests, i.e., pass a StringIO object instead.
