### ISSUE TITLE
SVGdigitizer workflow documentation

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/svgdigitizer#88]
Tasklist to improve the [svgdigitizer workflow documentation](https://github.com/echemdb/svgdigitizer/blob/master/doc/workflow.md):

- [x] Add link to the installation instructions of the `svgdigitizer` (see #125)
- [x] Link to metadata templates on `echemdb-metadata-schema`
- [x] Add description on x and y-axis unit usage (#Added #110 )
- [x] Describe sampling to test resulting plots from the SVG
- [x] Fixx eroenous figures with wrong axis labels (Added in #110)
- [x] Add documentation comment field (Added in #93 )
